# Dock general settings
[general]
position = "bottom"        # Options: bottom, top, left, right
auto_hide = true           # Automatically hide the dock when not in use
icon_size = 48             # Size of the icons in pixels

# Dock behavior settings
[behavior]
magnification = true       # Enable icon magnification on hover
magnification_factor = 1.5 # Magnification multiplier
app_name_on_hover = false

# Dock customization
[appearance]
main_color = "#403939"
edge_color = "#827676"
opacity = 0
border_thickness = 2
block_style = "box"         # box / island / none
dock_margins = 3


